# Generated by Django 4.1.1 on 2022-11-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('price_customized', models.FloatField()),
                ('category', models.CharField(choices=[('Rg', 'Reggaeton'), ('P', 'Pop'), ('I', 'Indie'), ('HH', 'Hip hop'), ('R', 'Rock')], max_length=2)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/tickets/')),
            ],
        ),
    ]
