# Generated by Django 4.1.1 on 2022-11-25 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ticket_stock'),
        ('main', '0006_alter_orderticket_user'),
    ]

    operations = [
    ]
