# Generated by Django 4.1.1 on 2022-11-25 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_merge_0003_ticket_stock_0006_alter_orderticket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tickets',
        ),
        migrations.AddField(
            model_name='orderticket',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.order'),
        ),
    ]
