# Generated by Django 4.1.1 on 2022-11-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_order_tickets_orderticket_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderticket',
            name='customized',
            field=models.BooleanField(default=False),
        ),
    ]
