# Generated by Django 4.1.1 on 2022-11-27 15:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_orderticket_customized'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderticket',
            name='billing_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.billingaddress'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 27, 15, 41, 16, 264552, tzinfo=datetime.timezone.utc)),
        ),
    ]
