# Generated by Django 4.1.1 on 2022-11-27 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_ticket_location_alter_order_ordered_date'),
        ('main', '0011_remove_orderticket_billing_address_and_more'),
    ]

    operations = [
    ]
