# Generated by Django 4.1.1 on 2022-11-27 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_order_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='optional_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 27, 16, 24, 51, 998321, tzinfo=datetime.timezone.utc)),
        ),
    ]
