# Generated by Django 4.1.1 on 2022-12-01 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_order_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 11, 11, 14, 717849, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='orderticket',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
