# Generated by Django 4.1.1 on 2022-12-05 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_order_ordered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderticket',
            name='color',
            field=models.CharField(choices=[('W', 'Blanco'), ('B', 'Negro'), ('G', 'Verde')], default='W', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='orderticket',
            name='model',
            field=models.IntegerField(choices=[('1', 'Modelo 1'), ('2', 'Modelo 2'), ('3', 'Modelo 3')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderticket',
            name='typing',
            field=models.CharField(choices=[('CS', 'Comic sans'), ('A', 'Arial'), ('C', 'Calibri')], default='CS', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 5, 12, 55, 3, 193025, tzinfo=datetime.timezone.utc)),
        ),
    ]
